### ISSUE TITLE
Add `bootupctl backend install` option to install BIOS bootloader

### ISSUE THREAD

**Issue by HuijingHei** [coreos/bootupd#398]
When build image, we install bootloader for uefi firmware when running `bootupctl backend install` (see https://github.com/coreos/coreos-assembler/blob/main/src/create_disk.sh#L407), for BIOS/PReP bootloader will call `grub2-install` (from cosa container). This is not consistent and convenient. 

What we want to do is add an option (for example -bios, or -noefi, etc) to cover BIOS/PReP firmware if run `bootupctl backend install`. See related issue https://github.com/coreos/coreos-assembler/issues/3156

**Comment by cgwalters** [comment]
To implement this we're basically adding a new "component" in bootupd terms.  Until now, bootupd has multiple layers of abstraction with the idea that it might be managing multiple things ("components") - specifically on x86_64, it could be managing both "bios" and "uefi".

But the abstractions haven't really been tested because we've only had one.

I'd probably say to start with just x86_64+bios i.e. a new "bios" component.  

To handle grub2-install for ppc64le we'd need to expand the set of architectures this project builds for - and probably in theory PReP/ppc64le would be a new distinct component ("openfirmware")?

### Simpler alternative

Add a new "grub2" component that is basically a thin wrapper around `grub2-install` and just records the version number - there'd be just a dummy data payload.  The more I think about it the more this probably makes sense.

**Comment by HuijingHei** [comment]
> Add a new "grub2" component that is basically a thin wrapper around `grub2-install` and just records the version number - there'd be just a dummy data payload. The more I think about it the more this probably makes sense.

This seems more simple and neat.

**Comment by HuijingHei** [comment]
Just curious, if failed to boot after firmware updated, should we consider the rollback?

**Comment by cgwalters** [comment]
This was done!
